//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sdi.rc
//
#define _VCRT_COMPILER_PREPROCESSOR     0
#define _USE_DECLSPECS_FOR_SAL          0
#define _USE_ATTRIBUTES_FOR_SAL         0
#define _HAS_CXX17                      0
#define _HAS_CXX20                      0
#define _HAS_NODISCARD                  0
#define _CRT_FUNCTIONS_REQUIRED         0
#define _CRT_HAS_CXX17                  0
#define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES 0
#define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT 0
#define _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES 0
#define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY 0
#define _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY 0
#define _HAS_EXCEPTIONS                 1
#define _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE 1
#define _CRT_BUILD_DESKTOP_APP          1
#define _CRT_INTERNAL_NONSTDC_NAMES     1
#define __STDC_WANT_SECURE_LIB__        1
#define EPERM                           1
#define VS_VERSION_INFO                 1
#define ENOENT                          2
#define ESRCH                           3
#define EINTR                           4
#define EIO                             5
#define ENXIO                           6
#define E2BIG                           7
#define _CRT_PACKING                    8
#define ENOEXEC                         8
#define EBADF                           9
#define ECHILD                          10
#define EAGAIN                          11
#define ENOMEM                          12
#define EACCES                          13
#define EFAULT                          14
#define IDM_ABOUT                       16
#define EBUSY                           16
#define IDM_OPENLOGS                    17
#define EEXIST                          17
#define IDM_LICENSE                     18
#define EXDEV                           18
#define IDM_DRVDIR                      19
#define ENODEV                          19
#define IDM_SEED                        20
#define _SAL_VERSION                    20
#define ENOTDIR                         20
#define IDM_UPDATES                     21
#define EISDIR                          21
#define IDM_UPDATES_SDI                 22
#define IDM_UPDATES_DRIVERS             23
#define ENFILE                          23
#define IDM_TOOLS                       24
#define EMFILE                          24
#define IDM_WELCOME                     25
#define ENOTTY                          25
#define IDM_TRANSLATE                   26
#define EFBIG                           27
#define ENOSPC                          28
#define ESPIPE                          29
#define EROFS                           30
#define EMLINK                          31
#define EPIPE                           32
#define EDOM                            33
#define EDEADLK                         36
#define ENAMETOOLONG                    38
#define ENOLCK                          39
#define ENOSYS                          40
#define ENOTEMPTY                       41
#define RESFILE                         100
#define _ARGMAX                         100
#define EADDRINUSE                      100
#define EADDRNOTAVAIL                   101
#define EAFNOSUPPORT                    102
#define EALREADY                        103
#define EBADMSG                         104
#define ECANCELED                       105
#define ECONNABORTED                    106
#define ECONNREFUSED                    107
#define ECONNRESET                      108
#define EDESTADDRREQ                    109
#define EHOSTUNREACH                    110
#define EIDRM                           111
#define EINPROGRESS                     112
#define EISCONN                         113
#define ELOOP                           114
#define EMSGSIZE                        115
#define ENETDOWN                        116
#define ENETRESET                       117
#define ENETUNREACH                     118
#define ENOBUFS                         119
#define ENODATA                         120
#define ENOLINK                         121
#define ENOMSG                          122
#define ENOPROTOOPT                     123
#define ENOSR                           124
#define ENOSTR                          125
#define ENOTCONN                        126
#define ENOTRECOVERABLE                 127
#define ENOTSOCK                        128
#define ENOTSUP                         129
#define EOPNOTSUPP                      130
#define EOTHER                          131
#define EOVERFLOW                       132
#define EOWNERDEAD                      133
#define EPROTO                          134
#define EPROTONOSUPPORT                 135
#define EPROTOTYPE                      136
#define ETIME                           137
#define ETIMEDOUT                       138
#define ETXTBSY                         139
#define EWOULDBLOCK                     140
#define IDI_ICON1                       200
#define IDR_CHECKED                     201
#define IDR_THEME                       202
#define IDR_LANG                        203
#define IDR_LICENSE                     204
#define IDR_UP                          205
#define IDR_DOWN                        206
#define IDR_UP_H                        207
#define IDR_DOWN_H                      208
#define IDR_INSTALL64                   209
#define IDR_CLI_HELP                    210
#define IDR_LOGO                        211
#define IDR_PATREON                     212
#define IDB_LOGO                        214
#define IDB_WATERMARK                   215
#define _SECURECRT_FILL_BUFFER_PATTERN  0xFE
#define VER_STATE                       0x102
#define SIZEY                           270
#define IDD_DIALOG1                     301
#define IDD_DIALOG2                     302
#define IDD_DIALOG3                     303
#define IDC_EDIT1                       304
#define IDACCEPT                        305
#define IDCHECKALL                      306
#define IDUNCHECKALL                    307
#define IDCHECKTHISPC                   308
#define IDLIST                          309
#define IDTOTALSIZE                     310
#define IDONLYUPDATE                    311
#define IDC_TAB1                        312
#define IDTOTALAVAIL                    313
#define IDKEEPSEEDING                   314
#define IDOPTIONS                       315
#define IDCHECKNETWORK                  316
#define IDSELECTION                     317
#define IDD_Page1                       400
#define IDD_P1_DRV                      401
#define IDD_P1_DRV1                     402
#define IDD_P1_DRV2                     403
#define IDD_P1_DRV3                     404
#define IDD_P1_ZOOMG                    405
#define IDD_P1_ZOOML                    406
#define IDD_P1_ZOOMR                    407
#define IDD_P1_ZOOMI                    408
#define IDD_P1_ZOOMB                    409
#define IDD_P1_ZOOMS                    410
#define IDD_P1_HINTG                    411
#define IDD_P1_HINTL                    412
#define IDD_P1_HINTE                    413
#define IDD_Page2                       500
#define IDD_P2_TOR                      501
#define IDD_P2_PORT                     502
#define IDD_P2_CON                      503
#define IDD_P2_DOWN                     504
#define IDD_P2_UP                       505
#define IDD_P2_PORTE                    506
#define IDD_P2_CONE                     507
#define IDD_P2_DOWNE                    508
#define IDD_P2_UPE                      509
#define IDD_P2_UPD                      510
#define IDD_P2_TURL                     511
#define IDD_P2_TURLE                    512
#define VER_INDEX                       0x205
#define IDD_Page3                       600
#define IDD_P3_DIR1                     601
#define IDD_P3_DIR2                     602
#define IDD_P3_DIR3                     603
#define IDD_P3_DIR4                     604
#define IDD_P3_DIR5                     605
#define IDD_P3_DIR1E                    606
#define IDD_P3_DIR2E                    607
#define IDD_P3_DIR3E                    608
#define IDD_P3_DIR4E                    609
#define IDD_P3_DIR5E                    610
#define IDD_Page4                       700
#define IDD_P4_CMDG                     701
#define IDD_P4_CMDL                     702
#define IDD_P4_CMD1                     703
#define IDD_P4_CMD2                     704
#define IDD_P4_CMD3                     705
#define IDD_P4_CMD1E                    706
#define IDD_P4_CMD2E                    707
#define IDD_P4_CMD3E                    708
#define IDD_P4_CONSL                    709
#define IDD_ABOUT                       800
#define IDD_ABOUT_T1                    801
#define IDD_ABOUT_T2                    802
#define IDD_ABOUT_T3                    803
#define IDD_ABOUT_T4                    804
#define IDD_ABOUT_T5                    805
#define IDD_ABOUT_T6                    806
#define IDD_ABOUT_T7                    808
#define IDD_ABOUT_T8                    809
#define IDD_ABOUT_T9                    810
#define IDC_SYSLINK1                    811
#define IDD_WELCOME                     900
#define IDD_WELC_TITLE                  901
#define IDD_WELC_SUBTITLE               902
#define IDD_WELC_INTRO                  903
#define IDD_WELC_INTRO2                 904
#define IDD_WELC_BUTTON1                905
#define IDD_WELC_BUTTON1_DESC           906
#define IDD_WELC_BUTTON2                907
#define IDD_WELC_BUTTON2_DESC           908
#define IDD_WELC_BUTTON3                909
#define IDD_WELC_BUTTON3_DESC           910
#define IDD_WELC_CLOSE                  911
#define IDD_WELC_LINK1                  912
#define IDD_WELC_LINK2                  913
#define IDD_WELC_TEXT                   920
// translation tool
#define IDD_TRANSL_EDITDIALOG           1000
#define IDC_TRANSL_KEYVALUE             1001
#define IDC_TRANSL_EDIT1                1002
#define IDC_TRANSL_EDIT2                1010
#define IDC_TRANSL_COPYCLIP             1011
#define IDC_TRANSL_CLEAR                1012
#define IDC_STATIC                      -1
#define IDS_APPTITLE                    10000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
