defaults:
  run:
    shell: cmd
jobs:
  VS2026-Build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          vs-prerelease: true
      - id: set_version
        name: Set version
        run: |
          CALL "Version.cmd" (ALPHA)
      - name: Build
        run: |
          msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ env.BUILD_CONFIGURATION }},Platform=${{ matrix.TARGET_PLATFORM }},ForceImportBeforeCppTargets=%GITHUB_WORKSPACE%\.vs\Generate.PDB.props
      - continue-on-error: true
        if: ${{ github.event_name == 'push' }}
        name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.TARGET_PLATFORM }}
          path: |
            ./*.exe
            ./*.pdb
    strategy:
      matrix:
        TARGET_PLATFORM:
          - x64
          - x86
name: VS2026
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - .gitignore
      - res/**
      - '**.cmd'
      - '**.md'
      - '**.rc'
      - '**.txt'
  push:
    branches:
      - dev
    paths-ignore:
      - .github/ISSUE_TEMPLATE/**
      - .gitignore
      - res/**
      - '**.cmd'
      - '**.md'
      - '**.rc'
      - '**.txt'
